//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成�?
//     运行时版�?2.0.50727.8000
//
//     对此文件的更改可能会导致不正确的行为，并且如�?
//     重新生成代码，这些更改将会丢失�?
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTeam.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等�?
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似�?ResGen �?Visual Studio 的工具自动生成的�?
    // 若要添加或移除成员，请编�?.ResX 文件，然后重新运�?ResGen
    // (�?/str 作为命令选项)，或重新生成 VS 项目�?
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓�?ResourceManager 实例�?
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iTeam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查�?
        ///   重写当前线程�?CurrentUICulture 属性�?
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
